#+TITLE: QuarkSuite Core (v2.0.0)
#+PROPERTY: header-args:deno :results output code :allow 'net

* Table of Contents :TOC@3:
- [[#summary][Summary]]
- [[#concepts][Concepts]]
  - [[#types][Types]]
    - [[#tokens][Tokens]]
    - [[#dictionary][Dictionary]]
  - [[#idioms][Idioms]]
    - [[#exporter][Exporter]]
- [[#api][API]]
  - [[#color][Color]]
    - [[#convertto-color][convert(to, color)]]
    - [[#adjustsettings-color][adjust(settings, color)]]
    - [[#mixsettings-color][mix(settings, color)]]
    - [[#harmonysettings-color][harmony(settings, color)]]
    - [[#visionsettings-color][vision(settings, color)]]
    - [[#contrastsettings-color][contrast(settings, color)]]
    - [[#illuminantsettings-color][illuminant(settings, color)]]
    - [[#palettesettings-color][palette(settings, color)]]
    - [[#accessibilitysettings-palette][accessibility(settings, palette)]]
    - [[#tokenspalette][tokens(palette)]]
    - [[#outputformat-dict][output(format, dict)]]
  - [[#content][Content]]
    - [[#textsettings-font][text(settings, font)]]
    - [[#mssettings-base][ms(settings, base)]]
    - [[#modifycalc-ms][modify(calc, ms)]]
    - [[#tokenssettings-ms][tokens(settings, ms)]]
  - [[#exporter-1][Exporter]]
    - [[#stylesheetformat-dict][stylesheet(format, dict)]]
    - [[#dataformat-dict][data(format, dict)]]
    - [[#interopformat-dict][interop(format, dict)]]
  - [[#workflow][Workflow]]
    - [[#presetaction-y][preset(action, y)]]
    - [[#processemitters][process(...emitters)]]
    - [[#pipelinex-emitters][pipeline(x, ...emitters)]]
    - [[#propagateemitter-xs][propagate(emitter, xs)]]
    - [[#delegatexs-emitters][delegate(xs, ...emitters)]]
- [[#extending-the-library][Extending the Library]]
- [[#next-steps][Next Steps]]

* Summary

This is the API documentation for QuarkSuite Core. It's a technical overview of everything you can do with the
library. For general use, you'll want to read the handbook instead. The utilities are organized based on the module
they're associated with.

This is a very straightforward document, but if something is unclear, please open an issue and let me know.

* Concepts

QuarkSuite Core has certain idioms based around its design, and it helps to be aware of them while reading.

** Types

When we talk about types in QuarkSuite, we mean /input and output/ types. This is signficant because it lets you know
what kind of data a utility takes and gives back. The types as of this writing are:

+ =color=: any valid CSS color string
+ =palette=: generated palette data
+ =ms=: generated modular scale data
+ =tokens=: assembled data object
+ =dict=: prepared data object with a required =project= property

Any type that is not explicitly mentioned here is local to the given utility. Now, let's go into a little more detail
about each type.

*** Tokens

Tokens in QuarkSuite are assembled data collections. If you're familiar with how they worked in v1, you should know that
it's changed significantly. Instead of manual assembly, token output now relies on assembling generated data into
conventional configurations.

This reduces a lot of the object creation boilerplate that v1 attempted to mitigate by providing the formula and
bootstrapper layers. Both are completely unnecessary in v2.

*** Dictionary

Dictionaries in QuarkSuite are packaged token collections. They're identified by a =project= object which exporting
functions require to be present (even if it's empty) before they will prepare tokens for use with their target formats.

Dictionaries are hierarchical and accommodate groups as you define them.

You can optionally define metadata at any group level or in the project settings themselves, but take care as some exporters will
ignore it depending on the format you use.

** Idioms

The included utilities are structured around three key idioms:

+ =action(y, x)=: a function that accepts type =x= and a =y= modifier to configure its output
+ =emitter(x)=: a function that accepts type =x= and emits output /directly from/ type =x=
+ =exporter(format, dict)=: a special action that accepts type =dict= and transforms its output based on a target =format=

*** Exporter

The shared rule between all exporters (with the exception of those for interop because they translate rather than
export): assume no access to the user's filesystem. The output of exporters is /file-ready/ for the target formats, but
you'll have to take it the rest of the way with your JS environment's native filesystem API or a library of your choice.

For security reasons, QuarkSuite does not generate output files.

* API

** Color

The =color.js= module contains all functionality related to creating and manipulating color, generating palettes, and
assembling color dictionaries.

You should be aware that all color processing happens in the Oklab color space. Using a perceptually uniform space like
Oklab was key in making color data composition and configurations both possible and predictable.

That said, every color /output/ is anchored in sRGB as that is the expected color space of the web.

*** convert(to, color)

An action that takes any valid CSS =color= and converts it =to= a given target format.

**** Parameters

+ =to: hex | rgb | hsl | cmyk | hwb | lab | lch | oklab | oklch=: the target format
+ =color: string=: the input color

**** Returns

+ =string=: the converted color

**** Example

#+BEGIN_SRC js
import { convert } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = "rebeccapurple";

// Highly recommend converting CSS Color Module 4/5 formats to hex, rgb, hsl
console.log(convert("hex", color)); // #663399
console.log(convert("rgb", color)); // rgb(102, 51, 153)
console.log(convert("hsl", color)); // hsl(270, 50%, 40%)

// When browsers are ready, you can use these
console.log(convert("cmyk", color)); // device-cmyk(33.333% 66.667% 0% 40%)
console.log(convert("hwb", color));  // hwb(270 20% 40%)
console.log(convert("lab", color)); // lab(32.393% 38.428 -47.69)
console.log(convert("lch", color)); // lch(32.393% 61.246 308.862)
console.log(convert("oklab", color)); // oklab(44.027% 0.08818 -0.13386)
console.log(convert("oklch", color)); // oklch(44.027% 0.1603 303.373)
#+END_SRC

**** Notes

+ Every color function in the library outputs colors in the format of the input color. The exception are named colors,
  which will *always* be converted to hexadecimal if used as input.

*** adjust(settings, color)

An action that takes any valid CSS =color= and adjusts its properties according to user =settings=.

**** Parameters

+ =settings: {}=: color adjustment settings
  + =settings.lightness = 0: number=: adjust the lightness of a color (as a percentage)
  + =settings.chroma = 0: number=: adjust the chroma/intensity of a color (as a percentage)
  + =settings.hue = 0: number=: adjust the hue of a color (in degrees)
  + =settings.alpha = 0: number=: adjust the alpha/transparency of a color (as a percentage)
  + =settings.steps = 0: number=: interpolates the color adjustment (up to number of steps)
+ =color: string=: the input color

**** Returns

+ =string | string[]=: the adjusted color or interpolation data

**** Example

#+BEGIN_SRC js
import { convert, adjust } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = convert("rgb", "rebeccapurple");

// You can adjust a single property
console.log(adjust({ lightness: 20 }, color)); // rgb(161, 112, 219)
console.log(adjust({ chroma: 50 }, color)); // rgb(119, 0, 206)
console.log(adjust({ hue: 120 }, color)); // rgb(140, 52, 0)

// Negative values mean a decrease
console.log(adjust({ lightness: -20 }, color)); // rgb(49, 0, 91)
console.log(adjust({ chroma: -50 }, color)); // rgb(86, 78, 99)
console.log(adjust({ hue: -120 }, color)); // rgb(0, 108, 92)
console.log(adjust({ alpha: -30 }, color)); // rgba(102, 51, 153, 0.7)

// You can adjust multiple properties
console.log(adjust({ lightness: 10, chroma: -20, hue: 90 }, color)); // rgb(165, 84, 67)
console.log(adjust({ chroma: 15, hue: -60 }, color)); // rgb(0, 83, 181)

// Interpolation activated
console.log(adjust({ lightness: 10, chroma: -50, hue: 360, steps: 5 }, color));
// [
//  "rgb(148, 47, 62)",
//  "rgb(120, 88, 0)",
//  "rgb(49, 114, 82)",
//  "rgb(67, 111, 134)",
//  "rgb(115, 106, 128)"
// ]
#+END_SRC

**** Notes

+ Percentage values lock at =±0-100=
+ Hue locks at =±0-360=

*** mix(settings, color)

An action that takes any valid CSS =color= and mixes it according to user =settings=.

**** Parameters

+ =settings: {}=: color blending settings
  + =settings.target = color: string=: set the blend target
  + =settings.strength = 0: number=: set the blend strength (as a percentage)
  + =settings.steps = 0: number=: interpolates the color blending (up to number of steps)
+ =color: string=: the input color

**** Returns

+ =string | string[]=: the blended color or interpolation data

**** Example

#+BEGIN_SRC js
import { convert, mix } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = convert("hsl", "rebeccapurple");
const target = "crimson";

// Blending toward the target color
console.log(mix({ target, strength: 0 }, color)); // hsl(270, 50, 40%)
console.log(mix({ target, strength: 25 }, color)); // hsl(296.154, 40.625%, 37.647%)
console.log(mix({ target, strength: 50 }, color)); // hsl(326.538, 48.148%, 42.353%)
console.log(mix({ target, strength: 75 }, color)); // hsl(341.538, 60.338%, 46.471%)
console.log(mix({ target, strength: 100 }, color));  // hsl(348, 83.333%, 47.059%)

// Blending from the target color
console.log(mix({ target, strength: -0 }, color)); // hsl(348, 83.333%, 47.059%)
console.log(mix({ target, strength: -25 }, color)); // hsl(341.538, 60.338%, 46.471%)
console.log(mix({ target, strength: -50 }, color)); // hsl(326.538, 48.148%, 42.353%)
console.log(mix({ target, strength: -75 }, color)); // hsl(296.154, 40.625%, 37.647%)
console.log(mix({ target, strength: -100 }, color));  // hsl(270, 50, 40%)

// Interpolation activated
console.log(mix({ target, strength: 100, steps: 5 }, color));
// [
//   "hsl(290.488, 42.268%, 38.039%)",
//   "hsl(316.484, 44.39%, 40.196%)",
//   "hsl(333.782, 52.889%, 44.118%)",
//   "hsl(343.421, 63.333%, 47.059%)",
//   "hsl(348, 83.333%, 47.059%)"
// ]
#+END_SRC

**** Notes

+ Percentage values lock at =±0-100=

*** harmony(settings, color)

An action that takes any valid CSS =color= and a generates an artistic color harmony according to user =settings=.

**** Parameters

+ =settings: {}=: color harmony settings
  + =settings.configuration = complementary: dyadic | complementary | analogous | split | triadic | clash | double |
    tetradic | square=: set the color harmony configuration
  + =settings.accented = false: boolean=: accented variant? (with =dyadic=, =analogous=, =split=, =triadic=)
+ =color: string=: the input color

**** Returns

+ =string[]=: the generated color harmony

**** Example

#+BEGIN_SRC js
import { convert, harmony } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = convert("hex", "rebeccapurple");

// Rotational harmonies
console.log(harmony({ configuration: "dyadic" }, color)); // ["#663399", "#832477"]
console.log(harmony({ configuration: "analogous" }, color)); // ["#663399", "#832477", "#931849"]
console.log(harmony({ configuration: "complementary" }, color)); // ["#663399", "#425e00"]

// Triadic harmonies
console.log(harmony({ configuration: "split" }, color)); // ["#663399", "#714c00", "#006921"]
console.log(harmony({ configuration: "triadic" }, color)); // ["#663399", "#8c3400", "#006c5c"]
console.log(harmony({ configuration: "clash" }, color)); // ["#663399", "#971e01", "#006587"]

// Tetradic harmonies
console.log(harmony({ configuration: "double" }, color)); // ["#663399", "#832477", "#425e00", "#006921"]
console.log(harmony({ configuration: "tetradic" }, color)); // ["#663399", "#931849", "#425e00", "#006c5c"]
console.log(harmony({ configuration: "square" }, color)); // ["#663399", "#971e01", "#425e00", "#006587"]

// Accented harmonies
console.log(harmony({ configuration: "dyadic", accented: true }, color)); // ["#663399", "#832477", "#425e00"]
console.log(harmony({ configuration: "analogous", accented: true }, color)); // ["#663399", "#832477", "#931849", "#425e00"]
console.log(harmony({ configuration: "split", accented: true }, color)); // ["#663399", "#714c00", "#425e00", "#006921"]
console.log(harmony({ configuration: "triadic", accented: true }, color)); // [ "#663399", "#8c3400", "#425e00", "#006c5c" ]
#+END_SRC

*** vision(settings, color)

An action that takes any valid CSS =color= and checks it against color vision deficiency (colorblindness) according to
user =settings=.

**** Parameters

+ =settings: {}=: color vision settings
  + =settings.as = protanopia: achromatopsia | protanopia | deuteranopia | tritanopia | protanomaly | deuteranomaly |
    tritanomaly=: set the color vision to check
  + =settings.method = brettel: brettel | vienot=: set the color vision algorithm
  + =settings.severity = 50: number=: set the severity (for anaomalous trichromacy checks as a percentage)
  + =settings.steps = 0: number=: interpolates the color vision checks (up to number of steps)
+ =color: string=: the input color

**** Returns

+ =string | string[]=: the color checked against color vision or interpolation data

**** Example

#+BEGIN_SRC js
import { convert, vision } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = convert("rgb", "rebeccapurple");

// Rod monochromatism (achromatopsia)
console.log(vision({ as: "achromatopsia" }, color)); // rgb(82, 82, 82)

// Dichromacy
console.log(vision({ as: "protanopia" }, color)); // rgb(0, 66, 153)
console.log(vision({ as: "deuteranopia" }, color)); // rgb(14, 83, 152)
console.log(vision({ as: "tritanopia" }, color)); // rgb(85, 76, 77)

// Anomalous trichromacy
console.log(vision({ as: "protanomaly" }, color)); // rgb(61, 59, 153)
console.log(vision({ as: "deuteranomaly" }, color)); // rgb(74, 69, 153)
console.log(vision({ as: "tritanomaly" }, color)); // rgb(94, 65, 123)

// Interpolation activated
console.log(vision({ as: "protanopia", steps: 5 }, color));
// [
//   "rgb(88, 54, 153)",
//   "rgb(71, 58, 153)",
//   "rgb(48, 61, 153)",
//   "rgb(0, 64, 153)",
//   "rgb(0, 66, 153)"
// ]
#+END_SRC

**** Notes

You'll notice that achromatomaly and blue-cone monochromatism (BCM) are missing.

This is a deliberate omission.

I realized that because of the sparse papers on cone monochromatism (and whether achromatomaly even is a correct term),
I wasn't comfortable with my attempts to implement it.

/Incomplete achromatopsia/ is the term that actually showed up in medical research, while the only references I've found
to achromatomaly were specific to CVD simulation research and implementation.

It feels strange that there's such a disparity between the vision science and software, so I concluded the responsible
choice was to not implement it at all.

If I find accurate algorithms to simulate them, I will in a future version. For now, doing so would be irresponsible of
me as a developer at the risk that someone might use these simulations to self-diagnose.

The =vision()= utility is intended for designers/developers to determine whether their colors are distinct enough to accomodate their
colorblind users and adjust them accordingly without having to rely on a browser extension or SVG filters.

It's definitely not intended for any kind of corrective image processing, so please don't.

*** contrast(settings, color)

An action that takes any valid CSS =color= and checks it against contrast sensitivity according to user =settings=.

**** Parameters

+ =settings: {}=: contrast sensitivity settings
  + =settings.factor = 0: number=: sets the gray factor to check against (as a percentage)
  + =settings.severity = 50: number=: set the severity of contrast loss (as a percentage)
  + =settings.steps = 0: number=: interpolates the contrast sensitivity check (up to number of steps)
+ =color: string=: the input color

**** Returns

+ =string | string[]=: the color checked against contrast sensitivity or interpolation data

**** Example

#+BEGIN_SRC js
import { convert, contrast } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = convert("hsl", "rebeccapurple");

// Factor percentage goes from black -> gray -> white
const severity = 50;
console.log(contrast({ factor: 0, severity }, color)); // hsl(270.698, 62.319%, 13.529%)
console.log(contrast({ factor: 25, severity }, color)); // hsl(266.667, 32.847%, 26.863%)
console.log(contrast({ factor: 50, severity }, color)); // hsl(265.714, 23.671%, 40.588%)
console.log(contrast({ factor: 75, severity }, color)); // hsl(265.882, 22.271%, 55.098%)
console.log(contrast({ factor: 100, severity }, color)); // hsl(264.906, 35.099%, 70.392%)

// Severity setting against factor 50 (pure gray)
const factor = 50;
console.log(contrast({ severity: 0, factor }, color)); // hsl(270, 50%, 40%)
console.log(contrast({ severity: 25, factor }, color)); // hsl(267.568, 35.577%, 40.784%)
console.log(contrast({ severity: 50, factor }, color)); // hsl(265.714, 23.671%, 40.588%)
console.log(contrast({ severity: 75, factor }, color)); // hsl(262.5, 11.765%, 40%)
console.log(contrast({ severity: 100, factor }, color)); // hsl(0, 0%, 38.824%)

// Interpolation activated
console.log(contrast({ factor, severity, steps: 5 }, color));
// [
//   "hsl(269.663, 49.171%, 35.49%)",
//   "hsl(269.231, 45.349%, 33.725%)",
//   "hsl(267.761, 38.728%, 33.922%)",
//   "hsl(266.316, 30.811%, 36.275%)",
//   "hsl(265.714, 23.671%, 40.588%)"
// ]
#+END_SRC

*** illuminant(settings, color)

An action that takes any valid CSS =color= and checks it against an illuminant (light source) according to user =settings=.

**** Parameters

+ =settings: {}=: illuminant settings
  + =settings.K = 1850: number=: sets the illuminant temperature (in Kelvin)
  + =settings.intensity = 50: number=: set the intensity of the illuminant (as a percentage)
  + =settings.steps = 0: number=: interpolates the illuminant check (up to number of steps)
+ =color: string=: the input color

**** Returns

+ =string | string[]=: the color checked against an illuminant or interpolation data

**** Example

#+BEGIN_SRC js
import { convert, illuminant } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = convert("hex", "rebeccapurple");

// Check the illuminants in order at 50% intensity:
// - candlelight (1850K)
// - incandescent bulb (2400K)
// - studio lamp (3200K)
// - tubular fluorescent lamps (5000K)
// - LCD screens (approximate) (6500K-9500K)
const intensity = 50;
console.log(illuminant({ K: 1850, intensity}, color)); // #ad6275
console.log(illuminant({ K: 2400, intensity}, color)); // #ad6d80
console.log(illuminant({ K: 3200, intensity}, color)); // #ad7a95
console.log(illuminant({ K: 5000, intensity}, color)); // #ae8db8
console.log(illuminant({ K: 7400, intensity}, color)); // #a58fcd

// Check illuminant candlelight at varying intensity
const K = 1850;
console.log(illuminant({ K, intensity: 0 }, color)); // #663399
console.log(illuminant({ K, intensity: 25 }, color)); // #884e8a
console.log(illuminant({ K, intensity: 50 }, color)); // #ad6275
console.log(illuminant({ K, intensity: 75 }, color)); // #d57457
console.log(illuminant({ K, intensity: 100 }, color)); // #ff8100

// Interpolation activated
console.log(illuminant({ K, intensity, steps: 5 }, color)); // ["#743a92", "#82408a", "#904682", "#9f537c", "#ad6275"]
#+END_SRC

*** palette(settings, color)

An action that takes any valid CSS =color= and generates a palette according to user =settings=.

**** Parameters

+ =settings: {}=: palette settings
  + =settings.configuration = material: material | artistic=: set the palette configuration
  + =settings.contrast = 100: number=: set the overall palette contrast (both configurations)
  + =settings.accents = false: boolean= include accent colors? (both configurations)
  + =settings.dark = false: boolean=: toggle dark mode? (both configurations)
  + =settings.states = false: boolean=: include interface states? (=material=)
  + =settings.tints = 3: number=: number of tints to generate (=artistic=)
  + =settings.tones = 3: number=: number of tones to generate (=artistic=)
  + =settings.shades = 3: number=: number of shades to generate (=artistic=)
+ =color: string=: the input color

**** Returns

+ =string[][]=: generated palette data

**** Examples

***** Material Configuration

#+BEGIN_SRC js
import { convert, palette } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = convert("hex", "rebeccapurple");

// Material configuration:
console.log(palette({ configuration: "material" }, color));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [
//       "#eeeaf6", "#d1c5e4",
//       "#b5a1d2", "#9a7dc0",
//       "#7f59ad", "#552e7e",
//       "#452964", "#35234b",
//       "#261c34", "#18151d"
//     ],
//     []
//   ],
//   []
// ]

// Material contrast adjustment
console.log(palette({ configuration: "material", contrast: 80 }, color));
// [
//   [ "#ded5ec", "#201929" ],
//   [
//     [
//       "#baa8d6", "#a991ca",
//       "#977abe", "#8663b2",
//       "#764ca6", "#5b3088",
//       "#512d77", "#462966",
//       "#3c2556", "#322146"
//     ],
//     []
//   ],
//   []
// ]

// Material with accents
console.log(palette({ configuration: "material", accents: true }, color));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [
//       "#eeeaf6", "#d1c5e4",
//       "#b5a1d2", "#9a7dc0",
//       "#7f59ad", "#552e7e",
//       "#452964", "#35234b",
//       "#261c34", "#18151d"
//     ],
//     [
//       "#d2f4ed", "#9cd6df",
//       "#70b5d7", "#5d8ece",
//       "#6063bb", "#640067",
//       "#58002a", "#420000",
//       "#1f0000", "#001c00"
//     ]
//   ],
//   []
// ]

// Material with interface states
console.log(palette({ configuration: "material", states: true }, color));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [
//       "#eeeaf6", "#d1c5e4",
//       "#b5a1d2", "#9a7dc0",
//       "#7f59ad", "#552e7e",
//       "#452964", "#35234b",
//       "#261c34", "#18151d"
//     ],
//     []
//   ],
//   [ "#908d95", "#368540", "#a48e3a", "#a63838" ]
// ]

// Material dark mode
console.log(palette({
  configuration: "material",
  dark: true,
  accents: true,
  states: true
}, color));
// [
//   [ "#111111", "#ffffff" ],
//   [
//     [
//       "#18151d", "#261c34",
//       "#35234b", "#452964",
//       "#552e7e", "#7f59ad",
//       "#9a7dc0", "#b5a1d2",
//       "#d1c5e4", "#eeeaf6"
//     ],
//     [
//       "#000000", "#000003",
//       "#000a25", "#001b51",
//       "#2e287b", "#a43ca5",
//       "#e4449b", "#ff5679",
//       "#ff7a1a", "#ffb200"
//     ]
//   ],
//   [ "#dedbe3", "#84d38a", "#f3dc89", "#fb857f" ]
// ]
#+END_SRC

***** Artistic Configuration

#+BEGIN_SRC js
import { convert, palette } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = convert("hex", "rebeccapurple");

// Artistic configuration:
console.log(palette({ configuration: "artistic" }, color));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [ "#9171ba", "#beadd8", "#eeeaf6" ],
//     [ "#795aa0", "#8e7da6", "#a39fa9" ],
//     [ "#4a2a6d", "#302143", "#18151d" ]
//   ],
//   []
// ]

// Artistic contrast adjustment
console.log(palette({ configuration: "artistic", contrast: 80 }, color));
// [
//   [ "#ded5ec", "#201929" ],
//   [
//     [ "#8865b3", "#ac95cc", "#d1c5e4" ],
//     [ "#75539f", "#856fa4", "#968aa8" ],
//     [ "#502c75", "#3a2553", "#261c34" ]
//   ],
//   []
// ]

// Artistic with adjusted variants
console.log(palette({
  configuration: "artistic",
  tints: 6,
  tones: 2,
  shades: 4
}, color));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [ "#7b53aa", "#9171ba", "#a78fc9", "#beadd8", "#d6cbe7", "#eeeaf6" ],
//     [ "#836ba3", "#a39fa9" ],
//     [ "#512d78", "#3d2658", "#2a1e39", "#18151d" ]
//   ],
//   []
// ]

// Artistic with omitted variants
console.log(palette({ configuration: "artistic", tints: 6, tones: 0, shades: 4 }, color));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [ "#7b53aa", "#9171ba", "#a78fc9", "#beadd8", "#d6cbe7", "#eeeaf6" ],
//     [],
//     [ "#512d78", "#3d2658", "#2a1e39", "#18151d" ]
//   ],
//   []
// ]

// Artistic with accents
console.log(palette({ configuration: "artistic", accents: true }, color));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [ "#9171ba", "#beadd8", "#eeeaf6" ],
//     [ "#795aa0", "#8e7da6", "#a39fa9" ],
//     [ "#4a2a6d", "#302143", "#18151d" ]
//   ],
//   [
//     "#6ad6eb", "#72aed7",
//     "#7386c3", "#6f5eae",
//     "#4e2c75", "#3b2659",
//     "#291f3f", "#191826",
//     "#08100f"
//   ]
// ]

// Artistic dark mode
console.log(palette({
  configuration: "artistic",
  accents: true,
  dark: true,
}, color));
// [
//   [ "#111111", "#ffffff" ],
//   [
//     [ "#9171ba", "#beadd8", "#eeeaf6" ],
//     [ "#795aa0", "#8e7da6", "#a39fa9" ],
//     [ "#4a2a6d", "#302143", "#18151d" ]
//   ],
//   [
//     "#6ad6eb", "#72aed7",
//     "#7386c3", "#6f5eae",
//     "#4e2c75", "#3b2659",
//     "#291f3f", "#191826",
//     "#08100f"
//   ]
// ]
#+END_SRC

**** Notes

The =material= configuration is especially suited for app palettes. If you include accents and interface states, you
likely won't need to generate any more colors for your app even after filtering for accessibility.

The =artistic= configuration is ideal for graphic design and content websites. The optional accents are generated much
like the material accents but are chromatically less extreme to reflect their different use case.

*** accessibility(settings, palette)

An action that takes generated =palette= data and filters it for accessibiility according to user =settings=.

**** Parameters

+ =settings: {}=: accessibility settings
  - =settings.mode = standard: standard | custom=: set the accessibility mode
  - =settings.rating = AA: AA | AAA=: set the WCAG contrast rating (=standard=)
  - =settings.large = false: boolean=: use adjusted contrast ratio for large text/UI? (=standard=)
  - =settings.min = 85: number=: minimum percentage of contrast against the background (=custom=)
  - =settings.max = undefined: number=: maximum percentage of contrast against the background (=custom=)
+ =palette: string[][]=: the input palette data

**** Returns

+ =string[][]=: the filtered palette data

**** Examples

***** Material Configuration

#+BEGIN_SRC js
import {
  convert,
  palette,
  accessibility
} = from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = convert("hex", "rebeccapurple");
const light = palette({ configuration: "material", accents: true }, color);
const dark = palette({ configuration: "material", accents: true, dark: true }, color);

// Valid colors for standard mode "AA" rating
console.log(accessibility({ mode: "standard", rating: "AA" }, light));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [ "#7f59ad", "#552e7e", "#452964", "#35234b", "#261c34", "#18151d" ],
//     [ "#6063bb", "#640067", "#58002a", "#420000", "#1f0000", "#001c00" ]
//   ],
//   []
// ]

// Valid colors for standard mode "AA" rating (dark)
console.log(accessibility({ mode: "standard", rating: "AA" }, dark));
// [
//   [ "#111111", "#ffffff" ],
//   [
//     [ "#9a7dc0", "#b5a1d2", "#d1c5e4", "#eeeaf6" ],
//     [ "#e4449b", "#ff5679", "#ff7a1a", "#ffb200" ]
//   ],
//   []
// ]

// Valid colors for standard mode "AA" large rating
console.log(accessibility({ mode: "standard", rating: "AA", large: true }, light));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [
//       "#9a7dc0",
//       "#7f59ad",
//       "#552e7e",
//       "#452964",
//       "#35234b",
//       "#261c34",
//       "#18151d"
//     ],
//     [
//       "#5d8ece",
//       "#6063bb",
//       "#640067",
//       "#58002a",
//       "#420000",
//       "#1f0000",
//       "#001c00"
//     ]
//   ],
//   []
// ]

// Valid colors for standard mode "AA" large rating (dark)
console.log(accessibility({ mode: "standard", rating: "AA", large: true }, dark));
// [
//   [ "#111111", "#ffffff" ],
//   [
//     [ "#7f59ad", "#9a7dc0", "#b5a1d2", "#d1c5e4", "#eeeaf6" ],
//     [ "#a43ca5", "#e4449b", "#ff5679", "#ff7a1a", "#ffb200" ]
//   ],
//   []
// ]

// Valid colors for standard mode "AAA" rating
console.log(accessibility({ mode: "standard", rating: "AAA" }, light));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [ "#552e7e", "#452964", "#35234b", "#261c34", "#18151d" ],
//     [ "#640067", "#58002a", "#420000", "#1f0000", "#001c00" ]
//   ],
//   []
// ]

// Valid colors for standard mode "AAA" rating (dark)
console.log(accessibility({ mode: "standard", rating: "AAA" }, dark));
// [
//   [ "#111111", "#ffffff" ],
//   [ [ "#b5a1d2", "#d1c5e4", "#eeeaf6" ], [ "#ff7a1a", "#ffb200" ] ],
//   []
// ]

// Valid colors for custom mode at 70% contrast from background
console.log(accessibility({ mode: "custom", min: 70 }, light));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [ "#35234b", "#261c34", "#18151d" ],
//     [ "#58002a", "#420000", "#1f0000", "#001c00" ]
//   ],
//   []
// ]

// Valid colors for custom mode at 50% contrast from background (dark)
console.log(accessibility({ mode: "custom", min: 50 }, dark));
// [
//   [ "#111111", "#ffffff" ],
//   [ [ "#b5a1d2", "#d1c5e4", "#eeeaf6" ], [ "#ff5679", "#ff7a1a", "#ffb200" ] ],
//   []
// ]

// Valid colors for custom mode at 55-75% contrast from background
console.log(accessibility({ mode: "custom", min: 55, max: 75 }, light));
// [
//   [ "#ffffff", "#111111" ],
//   [ [ "#552e7e", "#452964", "#35234b", "#261c34" ], [ "#640067", "#58002a" ] ],
//   []
// ]

// Valid colors for custom mode at 45-60% contrast from background (dark)
console.log(accessibility({ mode: "custom", min: 45, max: 60 }, dark));
// [
//   [ "#111111", "#ffffff" ],
//   [ [ "#9a7dc0", "#b5a1d2" ], [ "#e4449b", "#ff5679", "#ff7a1a" ] ],
//   []
// ]
#+END_SRC

***** Artistic Configuration

#+BEGIN_SRC js
import {
  convert,
  palette,
  accessibility
} from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = convert("hex", "rebeccapurple");
const values = 10;
const variants = { tints: values, tones: values, shades: values };
const light = palette({ configuration: "artistic", ...variants, accents: true, }, color);
const dark = palette({ configuration: "artistic", ...variants, accents: true, dark: true }, color);

// Valid colors for standard mode "AA" rating
console.log(accessibility({ mode: "standard", rating: "AA" }, light));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [ "#7247a3", "#7f59ad" ],
//     [ "#6c409b", "#714b9e", "#7756a0", "#7d61a2", "#836ba3" ],
//     [
//       "#5d318b", "#552e7e",
//       "#4d2b71", "#452964",
//       "#3d2658", "#35234b",
//       "#2e203f", "#261c34",
//       "#1f1928", "#18151d"
//     ]
//   ],
//   [ "#6f5eae", "#4e2c75", "#3b2659", "#291f3f", "#191826", "#08100f" ]
// ]

// Valid colors for standard mode "AA" rating (dark)
console.log(accessibility({ mode: "standard", rating: "AA" }, dark));
// [
//   [ "#111111", "#ffffff" ],
//   [
//     [
//       "#9a7dc0",
//       "#a78fc9",
//       "#b5a1d2",
//       "#c3b3db",
//       "#d1c5e4",
//       "#e0d7ed",
//       "#eeeaf6"
//     ],
//     [ "#8a76a5", "#9080a6", "#968aa8", "#9c94a9", "#a39fa9" ],
//     []
//   ],
//   [ "#6ad6eb", "#72aed7", "#7386c3" ]
// ]

// Valid colors for standard mode "AA" large rating
console.log(accessibility({ mode: "standard", rating: "AA", large: true }, light));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [ "#7247a3", "#7f59ad", "#8c6bb6", "#9a7dc0" ],
//     [
//       "#6c409b", "#714b9e",
//       "#7756a0", "#7d61a2",
//       "#836ba3", "#8a76a5",
//       "#9080a6", "#968aa8"
//     ],
//     [
//       "#5d318b", "#552e7e",
//       "#4d2b71", "#452964",
//       "#3d2658", "#35234b",
//       "#2e203f", "#261c34",
//       "#1f1928", "#18151d"
//     ]
//   ],
//   [
//     "#7386c3",
//     "#6f5eae",
//     "#4e2c75",
//     "#3b2659",
//     "#291f3f",
//     "#191826",
//     "#08100f"
//   ]
// ]

// Valid colors for standard mode "AA" large rating (dark)
console.log(accessibility({ mode: "standard", rating: "AA", large: true }, dark));
// [
//   [ "#111111", "#ffffff" ],
//   [
//     [
//       "#7f59ad", "#8c6bb6",
//       "#9a7dc0", "#a78fc9",
//       "#b5a1d2", "#c3b3db",
//       "#d1c5e4", "#e0d7ed",
//       "#eeeaf6"
//     ],
//     [
//       "#7756a0", "#7d61a2",
//       "#836ba3", "#8a76a5",
//       "#9080a6", "#968aa8",
//       "#9c94a9", "#a39fa9"
//     ],
//     []
//   ],
//   [ "#6ad6eb", "#72aed7", "#7386c3", "#6f5eae" ]
// ]

// Valid colors for standard mode "AAA" rating
console.log(accessibility({ mode: "standard", rating: "AAA" }, light));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [],
//     [ "#6c409b" ],
//     [
//       "#5d318b", "#552e7e",
//       "#4d2b71", "#452964",
//       "#3d2658", "#35234b",
//       "#2e203f", "#261c34",
//       "#1f1928", "#18151d"
//     ]
//   ],
//   [ "#4e2c75", "#3b2659", "#291f3f", "#191826", "#08100f" ]
// ]

// Valid colors for standard mode "AAA" rating (dark)
console.log(accessibility({ mode: "standard", rating: "AAA" }, dark));
// [
//   [ "#111111", "#ffffff" ],
//   [ [ "#b5a1d2", "#c3b3db", "#d1c5e4", "#e0d7ed", "#eeeaf6" ], [ "#a39fa9" ], [] ],
//   [ "#6ad6eb", "#72aed7" ]
// ]

// Valid colors for custom mode at 50% contrast from background
console.log(accessibility({ mode: "custom", min: 50 }, light));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [ "#7247a3" ],
//     [ "#6c409b", "#714b9e" ],
//     [
//       "#5d318b", "#552e7e",
//       "#4d2b71", "#452964",
//       "#3d2658", "#35234b",
//       "#2e203f", "#261c34",
//       "#1f1928", "#18151d"
//     ]
//   ],
//   [ "#4e2c75", "#3b2659", "#291f3f", "#191826", "#08100f" ]
// ]

// Valid colors for custom mode at 50% contrast from background (dark)
console.log(accessibility({ mode: "custom", min: 50 }, dark));
// [
//   [ "#111111", "#ffffff" ],
//   [
//     [ "#a78fc9", "#b5a1d2", "#c3b3db", "#d1c5e4", "#e0d7ed", "#eeeaf6" ],
//     [ "#9c94a9", "#a39fa9" ],
//     []
//   ],
//   [ "#6ad6eb", "#72aed7" ]
// ]

// Valid colors for custom mode at 50-70% contrast from background
console.log(accessibility({ mode: "custom", min: 50, max: 70 }, light));
// [
//   [ "#ffffff", "#111111" ],
//   [
//     [ "#7247a3" ],
//     [ "#6c409b", "#714b9e" ],
//     [ "#5d318b", "#552e7e", "#4d2b71", "#452964", "#3d2658" ]
//   ],
//   [ "#4e2c75", "#3b2659" ]
// ]

// Valid colors for custom mode at 50-70% contrast from background (dark)
console.log(accessibility({ mode: "custom", min: 50, max: 70 }, dark));
// [
//   [ "#111111", "#ffffff" ],
//   [ [ "#a78fc9", "#b5a1d2", "#c3b3db", "#d1c5e4" ], [ "#9c94a9", "#a39fa9" ], [] ],
//   [ "#6ad6eb", "#72aed7" ]
// ]
#+END_SRC

**** Notes

Remember that QuarkSuite palette data is nothing but an array with static grouping.

If you want to check the accessibility of color variants against an arbitrary background, you can change the background
color in the surface grouping (=[bg, fg]=) and the accessibility utility will use it as the background context.

If you want to check the accessibility of a random grouping of variants, you can swap out the variants grouping =[main,
accents]= with your own colors. The function only cares that the shape of the palette data matches a known
configuration. It doesn't necessarily care what kind of colors are grouped.

The reason for this major shift from v1 in packaging palette data is because I realized there should be a straight path
from a base color to a fully accessible palette.

The user is still free to access the assembled data for further transformation in any way they want, but the actual
palette creation process is intentionally simple.

*** tokens(palette)

An emitter that takes generated =palette= data and assembles it into a collection of color tokens for use as-is or with
an exporter.

**** Parameter

+ =palette: string[][]=: the generated palette data

**** Returns

={}=: assembled color tokens

**** Example

#+BEGIN_SRC js
import {
  convert,
  palette,
  accessibility,
  tokens
} = from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = convert("rgb", "rebeccapurple");

const contrast = 95;
const material = palette({ contrast, accents: true, states: true }, color);
const materialDark = palette({ contrast, accents: true, dark: true, states: true }, color);

const materialUI = accessibility({ rating: "AA", large: true }, material);
const materialHeading = accessibility({ rating: "AA" }, material);
const materialText = accessibility({ rating: "AAA" }, material);

const materialDarkUI = accessibility({ rating: "AA", large: true }, materialDark);
const materialDarkHeading = accessibility({ rating: "AA" }, materialDark);
const materialDarkText = accessibility({ rating: "AAA" }, materialDark);

// Accessible material UI (AA large)
console.log(tokens(materialUI));
// {
//   50: "rgb(148, 118, 188)",
//   100: "rgb(125, 86, 171)",
//   200: "rgb(87, 47, 129)",
//   300: "rgb(72, 42, 105)",
//   400: "rgb(58, 36, 82)",
//   500: "rgb(44, 31, 61)",
//   600: "rgb(31, 25, 40)",
//   bg: "rgb(247, 245, 250)",
//   fg: "rgb(21, 19, 23)",
//   a50: "rgb(99, 140, 206)",
//   a100: "rgb(102, 103, 189)",
//   a200: "rgb(107, 20, 112)",
//   a300: "rgb(96, 14, 55)",
//   a400: "rgb(76, 9, 9)",
//   a500: "rgb(45, 4, 5)",
//   a600: "rgb(4, 28, 6)",
//   state: {
//     pending: "rgb(145, 140, 152)",
//     success: "rgb(60, 132, 73)",
//     warning: "rgb(163, 141, 68)",
//     error: "rgb(165, 58, 64)"
//   }
// }

// Accessible material dark UI (AA large)
console.log(tokens(materialDarkUI));
// {
//   50: "rgb(125, 86, 171)",
//   100: "rgb(148, 118, 188)",
//   200: "rgb(173, 150, 205)",
//   300: "rgb(198, 183, 221)",
//   400: "rgb(224, 216, 237)",
//   bg: "rgb(21, 19, 23)",
//   fg: "rgb(247, 245, 250)",
//   a50: "rgb(211, 66, 152)",
//   a100: "rgb(244, 80, 126)",
//   a200: "rgb(245, 110, 68)",
//   a300: "rgb(246, 157, 38)"
//   state: {
//     pending: "rgb(215, 210, 223)",
//     success: "rgb(128, 202, 138)",
//     warning: "rgb(235, 211, 137)",
//     error: "rgb(242, 127, 128)"
//   }
// }

// Accessible material heading (AA)
console.log(tokens(materialHeading));
// {
//   50: "rgb(125, 86, 171)",
//   100: "rgb(87, 47, 129)",
//   200: "rgb(72, 42, 105)",
//   300: "rgb(58, 36, 82)",
//   400: "rgb(44, 31, 61)",
//   500: "rgb(31, 25, 40)",
//   bg: "rgb(247, 245, 250)",
//   fg: "rgb(21, 19, 23)",
//   a50: "rgb(102, 103, 189)",
//   a100: "rgb(107, 20, 112)",
//   a200: "rgb(96, 14, 55)",
//   a300: "rgb(76, 9, 9)",
//   a400: "rgb(45, 4, 5)",
//   a500: "rgb(4, 28, 6)"
//   state: {
//     pending: "rgb(145, 140, 152)",
//     success: "rgb(60, 132, 73)",
//     warning: "rgb(163, 141, 68)",
//     error: "rgb(165, 58, 64)"
//   }
// }

// Accessible material dark heading (AA)
console.log(tokens(materialDarkHeading));
// {
//   50: "rgb(148, 118, 188)",
//   100: "rgb(173, 150, 205)",
//   200: "rgb(198, 183, 221)",
//   300: "rgb(224, 216, 237)",
//   bg: "rgb(21, 19, 23)",
//   fg: "rgb(247, 245, 250)",
//   a50: "rgb(244, 80, 126)",
//   a100: "rgb(245, 110, 68)",
//   a200: "rgb(246, 157, 38)",
//   state: {
//     pending: "rgb(215, 210, 223)",
//     success: "rgb(128, 202, 138)",
//     warning: "rgb(235, 211, 137)",
//     error: "rgb(242, 127, 128)"
//   }
// }

// Accessible material text (AAA)
console.log(tokens(materialText));
// {
//   50: "rgb(87, 47, 129)",
//   100: "rgb(72, 42, 105)",
//   200: "rgb(58, 36, 82)",
//   300: "rgb(44, 31, 61)",
//   400: "rgb(31, 25, 40)",
//   bg: "rgb(247, 245, 250)",
//   fg: "rgb(21, 19, 23)",
//   a50: "rgb(107, 20, 112)",
//   a100: "rgb(96, 14, 55)",
//   a200: "rgb(76, 9, 9)",
//   a300: "rgb(45, 4, 5)",
//   a400: "rgb(4, 28, 6)",
//   state: {
//     pending: "rgb(145, 140, 152)",
//     success: "rgb(60, 132, 73)",
//     warning: "rgb(163, 141, 68)",
//     error: "rgb(165, 58, 64)"
//   }
// }

// Accessible material dark text (AAA)
console.log(tokens(materialDarkText));
// {
//   "50": "rgb(198, 183, 221)",
//   "100": "rgb(224, 216, 237)",
//   bg: "rgb(21, 19, 23)",
//   fg: "rgb(247, 245, 250)",
//   a50: "rgb(246, 157, 38)",
//   state: {
//     pending: "rgb(215, 210, 223)",
//     success: "rgb(128, 202, 138)",
//     warning: "rgb(235, 211, 137)",
//     error: "rgb(242, 127, 128)"
//   }
// }
#+END_SRC

*** output(format, dict)

An exporter that takes a complete color =dict= and prepares it for a given palette =format=.

**** Parameters

+ =format: gpl | sketchpalette=: the target palette format
+ =dict: {}=: the input color dictionary

**** Returns

=string=: file-ready exported palette

**** Example

#+BEGIN_SRC js
import {
  convert,
  palette,
  accessibility,
  tokens,
  output
} from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";

const color = convert("hex", "rebeccapurple");

const contrast = 80;
const graphic = palette({
  configuration: "artistic",
  contrast,
  tints: 5,
  tones: 3,
  shades: 4,
  accents: true,
}, color);

const graphicDark = palette({
  configuration: "artistic",
  contrast,
  tints: 5,
  tones: 3,
  shades: 4,
  accents: true,
  dark: true
}, color);

const highContrast = accessibility({ rating: "AAA" }, graphic);
const highContrastDark = accessibility({ rating: "AAA" }, graphicDark);

const dict = {
  project: {
    name: "High Contrast Accessible Palette",
    author: "Chatman R. Jr",
    license: "Attribution 4.0 International (CC BY 4.0)",
    version: "0.1.0"
  },
  light: tokens(highContrast),
  dark: tokens(highContrastDark)
};

// GIMP/Inkscape Palette
console.log(output("gpl", dict));
// GIMP Palette
// Name: High Contrast Accessible Palette (v0.1.0)
// # Owned by Chatman R. Jr
// # License: Attribution 4.0 International (CC BY 4.0)
// # 4/30/2022 2:55:38 PM
//
// Columns: 6
// 222	213	236	LIGHT BG (#ded5ec)
//  32	 25	 41	LIGHT FG (#201929)
//  85	 46	126	LIGHT DARK 100 (#552e7e)
//  69	 41	100	LIGHT DARK 200 (#452964)
//  53	 35	 75	LIGHT DARK 300 (#35234b)
//  38	 28	 52	LIGHT DARK 400 (#261c34)
//  61	 33	 87	LIGHT ACCENT 100 (#3d2157)
//  47	 26	 66	LIGHT ACCENT 200 (#2f1a42)
//  34	 19	 45	LIGHT ACCENT 300 (#22132d)
//  22	 13	 26	LIGHT ACCENT 400 (#160d1a)
//  11    6   8	LIGHT ACCENT 500 (#0b0608)
//  32	 25	 41	DARK BG (#201929)
// 222	213	236	DARK FG (#ded5ec)
// 187	168	214	DARK LIGHT 100 (#bba8d6)
// 209	197	228	DARK LIGHT 200 (#d1c5e4)
// 108	182	219	DARK ACCENT 100 (#6cb6db)

// Sketch Palette
console.log(output("sketchpalette", dict));
// {"colors":[{"red":0.8705882352941177,"green":0.8352941176470589,"blue":0.9254901960784314,"alpha":1},{"red":0.12549019607843137,"green":0.09803921568627451,"blue":0.1607843137254902,"alpha":1},{"red":0.3333333333333333,"green":0.1803921568627451,"blue":0.49411764705882355,"alpha":1},{"red":0.27058823529411763,"green":0.1607843137254902,"blue":0.39215686274509803,"alpha":1},{"red":0.20784313725490197,"green":0.13725490196078433,"blue":0.29411764705882354,"alpha":1},{"red":0.14901960784313725,"green":0.10980392156862745,"blue":0.20392156862745098,"alpha":1},{"red":0.23921568627450981,"green":0.12941176470588237,"blue":0.3411764705882353,"alpha":1},{"red":0.1843137254901961,"green":0.10196078431372549,"blue":0.25882352941176473,"alpha":1},{"red":0.13333333333333333,"green":0.07450980392156863,"blue":0.17647058823529413,"alpha":1},{"red":0.08627450980392157,"green":0.050980392156862744,"blue":0.10196078431372549,"alpha":1},{"red":0.043137254901960784,"green":0.023529411764705882,"blue":0.03137254901960784,"alpha":1},{"red":0.12549019607843137,"green":0.09803921568627451,"blue":0.1607843137254902,"alpha":1},{"red":0.8705882352941177,"green":0.8352941176470589,"blue":0.9254901960784314,"alpha":1},{"red":0.7333333333333333,"green":0.6588235294117647,"blue":0.8392156862745098,"alpha":1},{"red":0.8196078431372549,"green":0.7725490196078432,"blue":0.8941176470588236,"alpha":1},{"red":0.4235294117647059,"green":0.7137254901960784,"blue":0.8588235294117647,"alpha":1}],"pluginVersion":"1.4","compatibleVersion":"1.4"}
#+END_SRC

** Content

The =content.js= module contains all functionality around creating content tokens.

Modular scales are associated with the =ms= type and the goal is to create and enforce consistency in values used for
text sizing, content dimensions, spacing, layout, etc.

The content module also contains utilities for handling other kinds of content concerns.

*** text(settings, font)

An action that takes a =font= string and generates text tokens according to user =settings=.

**** Parameters

+ =settings: {}=: text settings
  - =settings.system = sans: sans | serif | monospace=: set system font stack
  - =settings.weights = [regular, bold]: Array<thin | extralight | light | regular | medium | semibold | bold |
    extrabold | black>=: set text weights
+ =font: string=: a custom font (or empty string)

**** Returns

={}=: generated text tokens

**** Example

#+BEGIN_SRC js
import { text } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/content.js";

// Change the system stack
console.log(text({ system: "serif", weights: ["regular", "bold"] }, ""));
// {
//   family: "Iowan Old Style, Apple Garamond, Baskerville, Times New Roman, Droid Serif, Times, Source Serif Pro,...",
//   regular: 400,
//   bold: 700
// }

// Each weight string corresponds with a given generated weight token
console.log(text({ system: "sans", weights: ["thin", "light", "black"] }, ""));
// {
//   family: "-apple-system, BlinkMacSystemFont, avenir next, avenir, helvetica neue, helvetica, Ubuntu, roboto, n...",
//   thin: 100,
//   light: 300,
//   black: 900
// }

// Set a font string and it will be prepended to the family
console.log(text({ system: "serif", weights: ["regular", "bold"] }, "Mozilla Slab"));
// {
//   family: "Mozilla Slab, Iowan Old Style, Apple Garamond, Baskerville, Times New Roman, Droid Serif, Times, Sou...",
//   regular: 400,
//   bold: 700
// }
#+END_SRC

*** ms(settings, base)

An action that takes a =base= value and generates modular scale data according to user =settings=.

**** Parameters

+ =settings: {}=: modular scale settings
  + =settings.ratio = 1.5: number | number[]=: set scale ratio(s)
  + =settings.values = 6: number=: set number of scale values
+ =base: number=: base value to generate from

**** Returns

=number[]=: modular scale data

**** Example

#+BEGIN_SRC js
import { ms } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/content.js";

// Setting ratio as 1.25
console.log(ms({ ratio: 1.25, values: 6 }, 1)); // [1, 1.25, 1.5625, 1.953125, 2.44140625, 3.0517578125]

// Multiple ratios can be set
console.log(ms({ ratio: [1.25, 1.5, 1.75], values: 6 }, 1)); // [1, 1.25, 1.5, 1.5625, 1.75, 2.25]

// Adjust output values
console.log(ms({ ratio: 1.5, values: 8 }, 1));
// [
//           1,        1.5,
//        2.25,      3.375,
//      5.0625,    7.59375,
//   11.390625, 17.0859375
// ]

// Set a different base
console.log(ms({ ratio: 1.5, values: 6 }, 16)); // [16, 24, 36, 54, 81, 121.5]
#+END_SRC

**** Notes

+ At this point, the precision of the output is untouched. Raw modular scales should remain unprocessed for precision to
  ensure recalculations are accurate as well. Precision comes in later.

*** modify(calc, ms)

An action that takes a generated =ms= and updates each value via a =calc= modifier.

**** Parameters

+ =calc: (n: number) => number=: the recalculation function
+ =ms: number[]=: the input modular scale data

**** Returns

=number[]=: the modified scale data

**** Example

#+BEGIN_SRC js
import { ms, modify } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/content.js";

const scale = ms({ ratio: 2, values: 6 }, 1);

// multiply each value by 1.2
console.log(modify((n) => n * 1.2, scale)); // [1.2, 2.4, 4.8, 9.6, 19.2, 38.4]

// divide each value by 10
console.log(modify((n) => n / 10, scale)); // [0.1, 0.2, 0.4, 0.8, 1.6, 3.2]
#+END_SRC

*** tokens(settings, ms)

An action that takes a generated =ms= and outputs content tokens according to user =settings=.

**** Parameters

+ =settings: {}=: content token settings
  - =settings.type = bidirectional: bidirectional | unidirectional | ranged | grid=: set the output type
  - =settings.unit = undefined: string | undefined=: set the output units (=bidirectional=, =unidirectional=, =ranged=)
  - =settings.inversion = undefined: string | undefined=: set the output units for the inverse (=bidirectional=)
  - =settings.min = 1: number=: set the minimum range value (=ranged=)
  - =settings.max = 1: number=: set the maximum range value (=ranged=)
  - =settings.trunc = false: boolean=: truncate the values? (=ranged=)
  - =settings.context = min: min | max=: set the token context (=ranged=)
+ =ms: number[]=: the input modular scale data

**** Returns

={}=: the generated content tokens

**** Examples

***** Bidirectional

#+BEGIN_SRC js
import { ms, tokens } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/content.js";

const scale = ms({ ratio: [1.414, 1.618], values: 6 }, 1);

// Unitless by default
console.log(tokens({ type: "bidirectional" }, scale));
// {
//   base: 1,
//   x2: 1.414,
//   x3: 1.618,
//   x4: 1.9994,
//   x5: 2.6179,
//   x6: 2.8271,
//   d2: 0.70721,
//   d3: 0.61805,
//   d4: 0.50015,
//   d5: 0.38198,
//   d6: 0.35371
// }

// As rems
console.log(tokens({ type: "bidirectional", unit: "rem" }, scale));
// {
//   base: "1rem",
//   x2: "1.414rem",
//   x3: "1.618rem",
//   x4: "1.9994rem",
//   x5: "2.6179rem",
//   x6: "2.8271rem",
//   d2: "0.70721rem",
//   d3: "0.61805rem",
//   d4: "0.50015rem",
//   d5: "0.38198rem",
//   d6: "0.35371rem"
// }

// As rems with em inversion
console.log(tokens({ type: "bidirectional", unit: "rem", inversion: "em" }, scale));
// {
//   base: "1rem",
//   x2: "1.414rem",
//   x3: "1.618rem",
//   x4: "1.9994rem",
//   x5: "2.6179rem",
//   x6: "2.8271rem",
//   d2: "0.70721em",
//   d3: "0.61805em",
//   d4: "0.50015em",
//   d5: "0.38198em",
//   d6: "0.35371em"
// }
#+END_SRC

***** Unidirectional

#+BEGIN_SRC js
import { ms, tokens } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/content.js";

const scale = ms({ ratio: [1.414, 1.618], values: 6 }, 1);

// Unitless by default
console.log(tokens({ type: "unidirectional" }, scale));
// {
//   base: 1,
//   x2: 1.414,
//   x3: 1.618,
//   x4: 1.9994,
//   x5: 2.6179,
//   x6: 2.8271,
// }

// As rems
console.log(tokens({ type: "unidirectional", unit: "rem" }, scale));
// {
//   base: "1rem",
//   x2: "1.414rem",
//   x3: "1.618rem",
//   x4: "1.9994rem",
//   x5: "2.6179rem",
//   x6: "2.8271rem",
// }
#+END_SRC

***** Ranged

#+BEGIN_SRC js
import { ms, tokens } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/content.js";

const scale = ms({ ratio: [1.414, 1.618], values: 6 }, 1);

// Unitless by default
console.log(tokens({ type: "ranged", min: 1, max: 10 }, scale));
// { base: 1, i2: 4.1834, i3: 4.4378, i4: 5.5014, i5: 6.5624, i6: 7.3649, max: 10 }

// Sample: A measure (characters per line) scale
console.log(tokens({
  type: "ranged",
  min: 45,
  max: 75,
  unit: "ch",
  trunc: true,
  context: "max"
}, scale));
// { base: "75ch", i2: "66ch", i3: "63ch", i4: "60ch", i5: "56ch", i6: "55ch", min: "45ch" }
#+END_SRC

***** Grid

#+BEGIN_SRC js
import { ms, tokens } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/content.js";

const scale = ms({ ratio: 1.618, values: 5 }, 1);

// Sample: Grid layout tokens
console.log(tokens({ type: "grid" }, scale));
// {
//   columns: 5,
//   rows: 3,
//   col: {
//     "1": 1,
//     "2": 2,
//     "3": 3,
//     "4": 4,
//     "5": 5,
//     "-1": -1,
//     "-2": -2,
//     "-3": -3,
//     "-4": -4,
//     "-5": -5
//   },
//   row: { "1": 1, "2": 2, "3": 3, "-1": -1, "-2": -2, "-3": -3 }
// }
#+END_SRC

**** Notes

=tokens()= is designed to generate (mostly) content modular scale tokens, but it can be used for /any/ kind of numeric
scale data. This means you can use it to generate tokens for, say, animation durations.

If you're coming from v1, this means that the content =tokens()= utility completely replaces formulas because it builds
on the fact that (generally) modular scales for content will be one of three configurations:

+ Bidirectional (=<- base ->=): base value, multiples, and inverse
+ Unidirectional (=base ->=): base value, multiples
+ Ranged (=min <-> max=): minimum value, generated intervals, maximum value

The =grid= type generates columns and rows as CSS grid tracks where columns are equivalent to the number of scale values
and rows are derived from the =columns / ratio=.

** Exporter

The =exporter.js= module handles all the functionality around outputting token dictionaries for various
formats. QuarkSuite does not assume filesystem access, so the output is /file-ready/ rather than a file itself. This
means you can directly write out to your filesystem using your environment's native API or a library of your choice.

Exporters are defined by the domain target and include:

+ =stylesheet()=: target is a stylesheet format (CSS custom properties, common preprocessors)
+ =data()=: target is a general data format (JSON, YAML)
+ =interop()=: target is interop spec (TailwindCSS theme, Style Dictionary tokens)

*** stylesheet(format, dict)

An exporter that takes a complete token =dict= and prepares a file-ready template string for a given stylesheet =format=.

**** Parameters

+ =format: css | scss | less | styl=: the target stylesheet format
+ =dict: {}=: the input token dictionary

**** Returns

=string=: file-ready stylesheet output

**** Example

#+BEGIN_SRC js
import {
  convert,
  palette,
  tokens: color
} from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";
import {
  text,
  ms,
  tokens: content
} from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/content.js";
import { stylesheet } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/exporter.js";

const swatch = convert("rgb", "rebeccapurple");
const scale = ms({ ratio: 1.414, values: 4 }, 1);

// Sample dictionary
const dict = {
  project: {
    name: "Sample Dictionary",
    author: "Ed N. Bacon",
    license: "MIT",
    version: "0.1.0"
  },
  sd: {
    color: color(palette({ configuration: "material", accents: true }, swatch)),
    text: {
      primary: text({ system: "sans", weights: ["regular", "bold"] }, ""),
      secondary: text({ system: "serif", weights: ["light", "bold", "black"] }, ""),
      size: content({ type: "bidirectional", unit: "rem", inversion: "em" }, scale),
      measure: content({
        type: "ranged",
        min: 45,
        max: 75,
        trunc: true,
        context: "max",
        unit: "ch",
      }, scale),
      leading: content({
        type: "ranged",
        min: 1.25,
        max: 1.5,
        context: "max",
      }, scale),
    },
    spacing: content({ type: "bidirectional", unit: "ex" }, scale)
  }
};

// CSS Custom Properties
console.log(stylesheet("css", dict));
//
// /**
//  * Project: Sample Dictionary (v0.1.0)
//  * Owned by: Ed N. Bacon
//  * License: MIT
//  * ================================================================================
//  *
//  * DESCRIPTION: N/A
//  * COMMENTS: N/A
//  * --------------------------------------------------------------------------------
//  * Updated on 5/11/2022 at 3:21:03 PM
//  **/
//
// :root {
//   --sd-color-50: rgb(238, 234, 246);
//   --sd-color-100: rgb(209, 197, 228);
//   --sd-color-200: rgb(181, 161, 210);
//   --sd-color-300: rgb(154, 125, 192);
//   --sd-color-400: rgb(127, 89, 173);
//   --sd-color-500: rgb(85, 46, 126);
//   --sd-color-600: rgb(69, 41, 100);
//   --sd-color-700: rgb(53, 35, 75);
//   --sd-color-800: rgb(38, 28, 52);
//   --sd-color-900: rgb(24, 21, 29);
//   --sd-color-bg: rgb(255, 255, 255);
//   --sd-color-fg: rgb(17, 17, 17);
//   --sd-color-a50: rgb(210, 244, 237);
//   --sd-color-a100: rgb(156, 214, 223);
//   --sd-color-a200: rgb(112, 181, 215);
//   --sd-color-a300: rgb(93, 142, 206);
//   --sd-color-a400: rgb(96, 99, 187);
//   --sd-color-a500: rgb(100, 0, 103);
//   --sd-color-a600: rgb(88, 0, 42);
//   --sd-color-a700: rgb(66, 0, 0);
//   --sd-color-a800: rgb(31, 0, 0);
//   --sd-color-a900: rgb(0, 28, 0);
//   --sd-text-primary-family: -apple-system, BlinkMacSystemFont, avenir next, avenir, helvetica neue, helvetica, Ubuntu, roboto, noto, segoe ui, arial, sans-serif;
//   --sd-text-primary-regular: 400;
//   --sd-text-primary-bold: 700;
//   --sd-text-secondary-family: Iowan Old Style, Apple Garamond, Baskerville, Times New Roman, Droid Serif, Times, Source Serif Pro, serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol;
//   --sd-text-secondary-light: 300;
//   --sd-text-secondary-bold: 700;
//   --sd-text-secondary-black: 900;
//   --sd-text-size: 1rem;
//   --sd-text-size-x2: 1.414rem;
//   --sd-text-size-x3: 1.9994rem;
//   --sd-text-size-x4: 2.8271rem;
//   --sd-text-size-d2: 0.70721em;
//   --sd-text-size-d3: 0.50015em;
//   --sd-text-size-d4: 0.35371em;
//   --sd-text-measure: 75ch;
//   --sd-text-measure-i2: 66ch;
//   --sd-text-measure-i3: 60ch;
//   --sd-text-measure-i4: 55ch;
//   --sd-text-measure-min: 45ch;
//   --sd-text-leading: 1.5;
//   --sd-text-leading-i2: 1.4268;
//   --sd-text-leading-i3: 1.375;
//   --sd-text-leading-i4: 1.3384;
//   --sd-text-leading-min: 1.25;
//   --sd-spacing: 1ex;
//   --sd-spacing-x2: 1.414ex;
//   --sd-spacing-x3: 1.9994ex;
//   --sd-spacing-x4: 2.8271ex;
//   --sd-spacing-d2: 0.70721ex;
//   --sd-spacing-d3: 0.50015ex;
//   --sd-spacing-d4: 0.35371ex;
//
// }
//

// Sass (SCSS) variables
console.log(stylesheet("scss", dict));
//
// /*!
//  * Project: Sample Dictionary (v0.1.0)
//  * Owned by: Ed N. Bacon
//  * License: MIT
//  * ================================================================================
//  *
//  * DESCRIPTION: N/A
//  * COMMENTS: N/A
//  * --------------------------------------------------------------------------------
//  * Updated on 5/11/2022 at 3:23:11 PM
//  */
//
// $sd-color-50: rgb(238, 234, 246);
// $sd-color-100: rgb(209, 197, 228);
// $sd-color-200: rgb(181, 161, 210);
// $sd-color-300: rgb(154, 125, 192);
// $sd-color-400: rgb(127, 89, 173);
// $sd-color-500: rgb(85, 46, 126);
// $sd-color-600: rgb(69, 41, 100);
// $sd-color-700: rgb(53, 35, 75);
// $sd-color-800: rgb(38, 28, 52);
// $sd-color-900: rgb(24, 21, 29);
// $sd-color-bg: rgb(255, 255, 255);
// $sd-color-fg: rgb(17, 17, 17);
// $sd-color-a50: rgb(210, 244, 237);
// $sd-color-a100: rgb(156, 214, 223);
// $sd-color-a200: rgb(112, 181, 215);
// $sd-color-a300: rgb(93, 142, 206);
// $sd-color-a400: rgb(96, 99, 187);
// $sd-color-a500: rgb(100, 0, 103);
// $sd-color-a600: rgb(88, 0, 42);
// $sd-color-a700: rgb(66, 0, 0);
// $sd-color-a800: rgb(31, 0, 0);
// $sd-color-a900: rgb(0, 28, 0);
// $sd-text-primary-family: -apple-system, BlinkMacSystemFont, avenir next, avenir, helvetica neue, helvetica, Ubuntu, roboto, noto, segoe ui, arial, sans-serif;
// $sd-text-primary-regular: 400;
// $sd-text-primary-bold: 700;
// $sd-text-secondary-family: Iowan Old Style, Apple Garamond, Baskerville, Times New Roman, Droid Serif, Times, Source Serif Pro, serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol;
// $sd-text-secondary-light: 300;
// $sd-text-secondary-bold: 700;
// $sd-text-secondary-black: 900;
// $sd-text-size: 1rem;
// $sd-text-size-x2: 1.414rem;
// $sd-text-size-x3: 1.9994rem;
// $sd-text-size-x4: 2.8271rem;
// $sd-text-size-d2: 0.70721em;
// $sd-text-size-d3: 0.50015em;
// $sd-text-size-d4: 0.35371em;
// $sd-text-measure: 75ch;
// $sd-text-measure-i2: 66ch;
// $sd-text-measure-i3: 60ch;
// $sd-text-measure-i4: 55ch;
// $sd-text-measure-min: 45ch;
// $sd-text-leading: 1.5;
// $sd-text-leading-i2: 1.4268;
// $sd-text-leading-i3: 1.375;
// $sd-text-leading-i4: 1.3384;
// $sd-text-leading-min: 1.25;
// $sd-spacing: 1ex;
// $sd-spacing-x2: 1.414ex;
// $sd-spacing-x3: 1.9994ex;
// $sd-spacing-x4: 2.8271ex;
// $sd-spacing-d2: 0.70721ex;
// $sd-spacing-d3: 0.50015ex;
// $sd-spacing-d4: 0.35371ex;
//

// Less variables
console.log(stylesheet("less", dict));
//
// /*
//  * Project: Sample Dictionary (v0.1.0)
//  * Owned by: Ed N. Bacon
//  * License: MIT
//  * ================================================================================
//  *
//  * DESCRIPTION: N/A
//  * COMMENTS: N/A
//  * --------------------------------------------------------------------------------
//  * Updated on 5/11/2022 at 3:23:11 PM
//  */
//
// @sd-color-50: rgb(238, 234, 246);
// @sd-color-100: rgb(209, 197, 228);
// @sd-color-200: rgb(181, 161, 210);
// @sd-color-300: rgb(154, 125, 192);
// @sd-color-400: rgb(127, 89, 173);
// @sd-color-500: rgb(85, 46, 126);
// @sd-color-600: rgb(69, 41, 100);
// @sd-color-700: rgb(53, 35, 75);
// @sd-color-800: rgb(38, 28, 52);
// @sd-color-900: rgb(24, 21, 29);
// @sd-color-bg: rgb(255, 255, 255);
// @sd-color-fg: rgb(17, 17, 17);
// @sd-color-a50: rgb(210, 244, 237);
// @sd-color-a100: rgb(156, 214, 223);
// @sd-color-a200: rgb(112, 181, 215);
// @sd-color-a300: rgb(93, 142, 206);
// @sd-color-a400: rgb(96, 99, 187);
// @sd-color-a500: rgb(100, 0, 103);
// @sd-color-a600: rgb(88, 0, 42);
// @sd-color-a700: rgb(66, 0, 0);
// @sd-color-a800: rgb(31, 0, 0);
// @sd-color-a900: rgb(0, 28, 0);
// @sd-text-primary-family: -apple-system, BlinkMacSystemFont, avenir next, avenir, helvetica neue, helvetica, Ubuntu, roboto, noto, segoe ui, arial, sans-serif;
// @sd-text-primary-regular: 400;
// @sd-text-primary-bold: 700;
// @sd-text-secondary-family: Iowan Old Style, Apple Garamond, Baskerville, Times New Roman, Droid Serif, Times, Source Serif Pro, serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol;
// @sd-text-secondary-light: 300;
// @sd-text-secondary-bold: 700;
// @sd-text-secondary-black: 900;
// @sd-text-size: 1rem;
// @sd-text-size-x2: 1.414rem;
// @sd-text-size-x3: 1.9994rem;
// @sd-text-size-x4: 2.8271rem;
// @sd-text-size-d2: 0.70721em;
// @sd-text-size-d3: 0.50015em;
// @sd-text-size-d4: 0.35371em;
// @sd-text-measure: 75ch;
// @sd-text-measure-i2: 66ch;
// @sd-text-measure-i3: 60ch;
// @sd-text-measure-i4: 55ch;
// @sd-text-measure-min: 45ch;
// @sd-text-leading: 1.5;
// @sd-text-leading-i2: 1.4268;
// @sd-text-leading-i3: 1.375;
// @sd-text-leading-i4: 1.3384;
// @sd-text-leading-min: 1.25;
// @sd-spacing: 1ex;
// @sd-spacing-x2: 1.414ex;
// @sd-spacing-x3: 1.9994ex;
// @sd-spacing-x4: 2.8271ex;
// @sd-spacing-d2: 0.70721ex;
// @sd-spacing-d3: 0.50015ex;
// @sd-spacing-d4: 0.35371ex;
//

// Stylus variables
console.log(stylesheet("styl", dict));
//
// /*!
//  * Project: Sample Dictionary (v0.1.0)
//  * Owned by: Ed N. Bacon
//  * License: MIT
//  * ================================================================================
//  *
//  * DESCRIPTION: N/A
//  * COMMENTS: N/A
//  * --------------------------------------------------------------------------------
//  * Updated on 5/11/2022 at 3:27:39 PM
//  */
//
// sd-color-50 = rgb(238, 234, 246)
// sd-color-100 = rgb(209, 197, 228)
// sd-color-200 = rgb(181, 161, 210)
// sd-color-300 = rgb(154, 125, 192)
// sd-color-400 = rgb(127, 89, 173)
// sd-color-500 = rgb(85, 46, 126)
// sd-color-600 = rgb(69, 41, 100)
// sd-color-700 = rgb(53, 35, 75)
// sd-color-800 = rgb(38, 28, 52)
// sd-color-900 = rgb(24, 21, 29)
// sd-color-bg = rgb(255, 255, 255)
// sd-color-fg = rgb(17, 17, 17)
// sd-color-a50 = rgb(210, 244, 237)
// sd-color-a100 = rgb(156, 214, 223)
// sd-color-a200 = rgb(112, 181, 215)
// sd-color-a300 = rgb(93, 142, 206)
// sd-color-a400 = rgb(96, 99, 187)
// sd-color-a500 = rgb(100, 0, 103)
// sd-color-a600 = rgb(88, 0, 42)
// sd-color-a700 = rgb(66, 0, 0)
// sd-color-a800 = rgb(31, 0, 0)
// sd-color-a900 = rgb(0, 28, 0)
// sd-text-primary-family = -apple-system, BlinkMacSystemFont, avenir next, avenir, helvetica neue, helvetica, Ubuntu, roboto, noto, segoe ui, arial, sans-serif
// sd-text-primary-regular = 400
// sd-text-primary-bold = 700
// sd-text-secondary-family = Iowan Old Style, Apple Garamond, Baskerville, Times New Roman, Droid Serif, Times, Source Serif Pro, serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol
// sd-text-secondary-light = 300
// sd-text-secondary-bold = 700
// sd-text-secondary-black = 900
// sd-text-size = 1rem
// sd-text-size-x2 = 1.414rem
// sd-text-size-x3 = 1.9994rem
// sd-text-size-x4 = 2.8271rem
// sd-text-size-d2 = 0.70721em
// sd-text-size-d3 = 0.50015em
// sd-text-size-d4 = 0.35371em
// sd-text-measure = 75ch
// sd-text-measure-i2 = 66ch
// sd-text-measure-i3 = 60ch
// sd-text-measure-i4 = 55ch
// sd-text-measure-min = 45ch
// sd-text-leading = 1.5
// sd-text-leading-i2 = 1.4268
// sd-text-leading-i3 = 1.375
// sd-text-leading-i4 = 1.3384
// sd-text-leading-min = 1.25
// sd-spacing = 1ex
// sd-spacing-x2 = 1.414ex
// sd-spacing-x3 = 1.9994ex
// sd-spacing-x4 = 2.8271ex
// sd-spacing-d2 = 0.70721ex
// sd-spacing-d3 = 0.50015ex
// sd-spacing-d4 = 0.35371ex
//
#+END_SRC

*** data(format, dict)

An exporter that takes a complete token =dict= and prepares a file-ready template string for a given data =format=.

**** Parameters

+ =format: json | yaml=: the target data format
+ =dict: {}=: the input token dictionary

**** Returns

=string=: file-ready data output

**** Example

#+BEGIN_SRC js
import {
  convert,
  palette,
  tokens: color
} from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";
import {
  text,
  ms,
  tokens: content
} from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/content.js";
import { data } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/exporter.js";

const swatch = convert("rgb", "rebeccapurple");
const scale = ms({ ratio: 1.414, values: 4 }, 1);

// Sample dictionary
const dict = {
  project: {
    name: "Sample Dictionary",
    author: "Ed N. Bacon",
    license: "MIT",
    version: "0.1.0"
  },
  sd: {
    color: color(palette({ configuration: "material", accents: true }, swatch)),
    text: {
      primary: text({ system: "sans", weights: ["regular", "bold"] }, ""),
      secondary: text({ system: "serif", weights: ["light", "bold", "black"] }, ""),
      size: content({ type: "bidirectional", unit: "rem", inversion: "em" }, scale),
      measure: content({
        type: "ranged",
        min: 45,
        max: 75,
        trunc: true,
        context: "max",
        unit: "ch",
      }, scale),
      leading: content({
        type: "ranged",
        min: 1.25,
        max: 1.5,
        context: "max",
      }, scale),
    },
    spacing: content({ type: "bidirectional", unit: "ex" }, scale)
  }
};

// JSON
console.log(data("json", dict));
// {
//   "project": {
//     "name": "Sample Dictionary",
//     "author": "Ed N. Bacon",
//     "license": "MIT",
//     "version": "0.1.0"
//   },
//   "tokens": {
//     "sd": {
//       "color": {
//         "50": "rgb(238, 234, 246)",
//         "100": "rgb(209, 197, 228)",
//         "200": "rgb(181, 161, 210)",
//         "300": "rgb(154, 125, 192)",
//         "400": "rgb(127, 89, 173)",
//         "500": "rgb(85, 46, 126)",
//         "600": "rgb(69, 41, 100)",
//         "700": "rgb(53, 35, 75)",
//         "800": "rgb(38, 28, 52)",
//         "900": "rgb(24, 21, 29)",
//         "bg": "rgb(255, 255, 255)",
//         "fg": "rgb(17, 17, 17)",
//         "a50": "rgb(210, 244, 237)",
//         "a100": "rgb(156, 214, 223)",
//         "a200": "rgb(112, 181, 215)",
//         "a300": "rgb(93, 142, 206)",
//         "a400": "rgb(96, 99, 187)",
//         "a500": "rgb(100, 0, 103)",
//         "a600": "rgb(88, 0, 42)",
//         "a700": "rgb(66, 0, 0)",
//         "a800": "rgb(31, 0, 0)",
//         "a900": "rgb(0, 28, 0)"
//       },
//       "text": {
//         "primary": {
//           "family": "-apple-system, BlinkMacSystemFont, avenir next, avenir, helvetica neue, helvetica, Ubuntu, roboto, noto, segoe ui, arial, sans-serif",
//           "regular": 400,
//           "bold": 700
//         },
//         "secondary": {
//           "family": "Iowan Old Style, Apple Garamond, Baskerville, Times New Roman, Droid Serif, Times, Source Serif Pro, serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
//           "light": 300,
//           "bold": 700,
//           "black": 900
//         },
//         "size": {
//           "base": "1rem",
//           "x2": "1.414rem",
//           "x3": "1.9994rem",
//           "x4": "2.8271rem",
//           "d2": "0.70721em",
//           "d3": "0.50015em",
//           "d4": "0.35371em"
//         },
//         "measure": {
//           "base": "75ch",
//           "i2": "66ch",
//           "i3": "60ch",
//           "i4": "55ch",
//           "min": "45ch"
//         },
//         "leading": {
//           "base": 1.5,
//           "i2": 1.4268,
//           "i3": 1.375,
//           "i4": 1.3384,
//           "min": 1.25
//         }
//       },
//       "spacing": {
//         "base": "1ex",
//         "x2": "1.414ex",
//         "x3": "1.9994ex",
//         "x4": "2.8271ex",
//         "d2": "0.70721ex",
//         "d3": "0.50015ex",
//         "d4": "0.35371ex"
//       }
//     }
//   }
// }

// YAML
console.log(data("yaml", dict));
//
// # Updated on 5/11/2022 at 3:33:56 PM
//
// project:
//   name: Sample Dictionary
//   author: Ed N. Bacon
//   license: MIT
//   version: 0.1.0
//
// tokens:
//   sd:
//     color:
//       50: rgb(238, 234, 246)
//       100: rgb(209, 197, 228)
//       200: rgb(181, 161, 210)
//       300: rgb(154, 125, 192)
//       400: rgb(127, 89, 173)
//       500: rgb(85, 46, 126)
//       600: rgb(69, 41, 100)
//       700: rgb(53, 35, 75)
//       800: rgb(38, 28, 52)
//       900: rgb(24, 21, 29)
//       bg: rgb(255, 255, 255)
//       fg: rgb(17, 17, 17)
//       a50: rgb(210, 244, 237)
//       a100: rgb(156, 214, 223)
//       a200: rgb(112, 181, 215)
//       a300: rgb(93, 142, 206)
//       a400: rgb(96, 99, 187)
//       a500: rgb(100, 0, 103)
//       a600: rgb(88, 0, 42)
//       a700: rgb(66, 0, 0)
//       a800: rgb(31, 0, 0)
//       a900: rgb(0, 28, 0)
//     text:
//       primary:
//         family: -apple-system, BlinkMacSystemFont, avenir next, avenir, helvetica neue, helvetica, Ubuntu, roboto, noto, segoe ui, arial, sans-serif
//         regular: 400
//         bold: 700
//       secondary:
//         family: Iowan Old Style, Apple Garamond, Baskerville, Times New Roman, Droid Serif, Times, Source Serif Pro, serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol
//         light: 300
//         bold: 700
//         black: 900
//       size:
//         base: 1rem
//         x2: 1.414rem
//         x3: 1.9994rem
//         x4: 2.8271rem
//         d2: 0.70721em
//         d3: 0.50015em
//         d4: 0.35371em
//       measure:
//         base: 75ch
//         i2: 66ch
//         i3: 60ch
//         i4: 55ch
//         min: 45ch
//       leading:
//         base: 1.5
//         i2: 1.4268
//         i3: 1.375
//         i4: 1.3384
//         min: 1.25
//     spacing:
//       base: 1ex
//       x2: 1.414ex
//       x3: 1.9994ex
//       x4: 2.8271ex
//       d2: 0.70721ex
//       d3: 0.50015ex
//       d4: 0.35371ex
//
#+END_SRC

*** interop(format, dict)

An exporter that takes a complete token =dict= and translates the schema to a given =format= data spec.

**** Parameters

+ =format: tailwindcss | styledictionary=: the target data spec
+ =dict: {}=: the input token dictionary

**** Returns

={}=: the output data

**** Example

#+BEGIN_SRC js
import {
  convert,
  palette,
  tokens: color
} from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js";
import {
  text,
  ms,
  tokens: content
} from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/content.js";
import { interop } from "https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/exporter.js";


const swatch = convert("rgb", "rebeccapurple");
const scale = ms({ ratio: 1.414, values: 4 }, 1);

// Sample dictionary
const dict = {
  sd: {
    color: color(palette({ configuration: "material", accents: true }, swatch)),
    text: {
      primary: text({ system: "sans", weights: ["regular", "bold"] }, ""),
      secondary: text({ system: "serif", weights: ["light", "bold", "black"] }, ""),
      size: content({ type: "bidirectional", unit: "rem", inversion: "em" }, scale),
      measure: content({
        type: "ranged",
        min: 45,
        max: 75,
        trunc: true,
        context: "max",
        unit: "ch",
      }, scale),
      leading: content({
        type: "ranged",
        min: 1.25,
        max: 1.5,
        context: "max",
      }, scale),
    },
    spacing: content({ type: "bidirectional", unit: "ex" }, scale)
  }
};

// TailwindCSS theme
console.log(interop("tailwindcss", {
  project: {},
  theme: {
    extend: {
      colors: { main: dict.sd.color },
      spacing: dict.sd.spacing
    },
  }
}));
// {
//   theme: {
//     extend: {
//       colors: { main: [Object] },
//       spacing: {
//         DEFAULT: "1ex",
//         x2: "1.414ex",
//         x3: "1.9994ex",
//         x4: "2.8271ex",
//         d2: "0.70721ex",
//         d3: "0.50015ex",
//         d4: "0.35371ex"
//       }
//     }
//   }
// }

// Style Dictionary tokens
console.log(interop("styledictionary", { project: {}, ...dict }));
// {
//   sd: {
//     color: {
//       "50": { value: "rgb(238, 234, 246)" },
//       "100": { value: "rgb(209, 197, 228)" },
//       "200": { value: "rgb(181, 161, 210)" },
//       "300": { value: "rgb(154, 125, 192)" },
//       "400": { value: "rgb(127, 89, 173)" },
//       "500": { value: "rgb(85, 46, 126)" },
//       "600": { value: "rgb(69, 41, 100)" },
//       "700": { value: "rgb(53, 35, 75)" },
//       "800": { value: "rgb(38, 28, 52)" },
//       "900": { value: "rgb(24, 21, 29)" },
//       bg: { value: "rgb(255, 255, 255)" },
//       fg: { value: "rgb(17, 17, 17)" },
//       a50: { value: "rgb(210, 244, 237)" },
//       a100: { value: "rgb(156, 214, 223)" },
//       a200: { value: "rgb(112, 181, 215)" },
//       a300: { value: "rgb(93, 142, 206)" },
//       a400: { value: "rgb(96, 99, 187)" },
//       a500: { value: "rgb(100, 0, 103)" },
//       a600: { value: "rgb(88, 0, 42)" },
//       a700: { value: "rgb(66, 0, 0)" },
//       a800: { value: "rgb(31, 0, 0)" },
//       a900: { value: "rgb(0, 28, 0)" }
//     },
//     text: {
//       primary: { family: [Object], regular: [Object], bold: [Object] },
//       secondary: { family: [Object], light: [Object], bold: [Object], black: [Object] },
//       size: {
//         base: [Object],
//         x2: [Object],
//         x3: [Object],
//         x4: [Object],
//         d2: [Object],
//         d3: [Object],
//         d4: [Object]
//       },
//       measure: { base: [Object], i2: [Object], i3: [Object], i4: [Object], min: [Object] },
//       leading: { base: [Object], i2: [Object], i3: [Object], i4: [Object], min: [Object] }
//     },
//     spacing: {
//       base: { value: "1ex" },
//       x2: { value: "1.414ex" },
//       x3: { value: "1.9994ex" },
//       x4: { value: "2.8271ex" },
//       d2: { value: "0.70721ex" },
//       d3: { value: "0.50015ex" },
//       d4: { value: "0.35371ex" }
//     }
//   }
// }
#+END_SRC

** Workflow

The =workflow.js= contains functionality around QuarkSuite's advanced data composition and reuse.

It's important to note that the workflow module changes nothing about the way data is actually generated. Its main
purpose is to expose /design patterns/ helpful to the advanced user.

Collectively, the workflow module replaces the /configuration/ and /formula/ idioms that featured in v1 (if you're familiar
with the last version).

*** preset(action, y)

A workflow helper that converts an =action= into an emitter by presetting its =y= modifier.

**** Parameters

+ =action: (y: unknown, x: unknown) => unknown>=: the action to convert
+ =y: unknown=: the action modifier to preset

**** Returns

+ =(x: unknown) => unknown=: the resultant emitter

**** Example

#+BEGIN_SRC deno
const {
  convert,
  adjust,
  mix
} = await import("https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js");
const { preset } = await import("https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/workflow.js");

const swatch = "rebeccapurple";

const hex = preset(convert, "hex");
const adjacent = preset(adjust, { hue: 30 });
const withRed = preset(mix, { target: "crimson", strength: 30 });

// swatch | hex -> adjacent -> withRed
console.log(withRed(adjacent(hex(swatch)))); // #9d276a

// order matters
console.log(adjacent(withRed(hex(swatch)))); // #99315a

// any color | hex -> adjacent -> withRed
console.log(withRed(adjacent(hex("dodgerblue")))); // #a46dc7
console.log(withRed(adjacent(hex("#ea7")))); // #de925b
console.log(withRed(adjacent(hex("rgb(25, 128, 33)")))); // #747558
console.log(withRed(adjacent(hex("hsl(210, 40%, 60%)")))); // #aa7a9d
#+END_SRC

**** Notes

Using =preset()= to convert actions into emitters is the starting point of /all/ advanced QuarkSuite usage. The remaining
helpers deal exclusively with harnessing the power unleashed by this simple function.

*** process(...emitters)

A workflow helper that combines a sequence of =emitters= into a new emitter.

**** Parameters

+ =emitters: Array<(x: unknown) => unknown>=: the sequence of emitters to combine

**** Returns

+ =(x: unknown) => unknown=: a new emitter from execution sequence

**** Example

#+BEGIN_SRC deno
const {
  convert,
  adjust,
  mix
} = await import("https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js");
const {
  preset,
  process
} = await import("https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/workflow.js");

const swatch = "rebeccapurple";

const hex = preset(convert, "hex");
const adjacent = preset(adjust, { hue: 30 });
const withRed = preset(mix, { target: "crimson", strength: 30 });

// Create primary (color) process
const primary = process(hex, adjacent, withRed);

// Processes are composable from other processes
const secondary = process(primary, adjacent);
const tertiary = process(secondary, adjacent, adjacent);

console.log(primary(swatch)); // #9d276a
console.log(secondary(swatch)) // #a72433
console.log(tertiary(swatch)); // #934800
#+END_SRC

**** Notes

Creating a =process= is ideal in situations where you want to repeat a sequence of transformations on different values
of the same type, but you don't know ahead of time exactly what those values will be.

It's a great way to create your own /configurations/ to share across projects.

*** pipeline(x, ...emitters)

A workflow helper that transforms data of type =x= through a sequence of =emitters=.

**** Parameters

+ =x: unknown=: the data to pass through
+ =emitters: Array<(x: unknown) => unknown>=: the sequence of emitters to execute

**** Returns

=unknown=: the transformed data

**** Example

#+BEGIN_SRC deno
const {
  convert,
  adjust,
  mix
} = await import("https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js");
const {
  preset,
  process,
  pipeline
} = await import("https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/workflow.js");

const swatch = "rebeccapurple";

const hex = preset(convert, "hex");
const adjacent = preset(adjust, { hue: 30 });
const withRed = preset(mix, { target: "crimson", strength: 30 });

// Create primary (color) process
const primary = process(hex, adjacent, withRed);

const main = pipeline(swatch, primary);

// The output of a pipeline can be used as the input of other pipelines
const accent = pipeline(main, adjacent);
const highlight = pipeline(accent, adjacent, adjacent, withRed);

console.log({ main, accent, highlight });
// { main: "#9d276a", accent: "#a72433", highlight: "#a9411a" }
#+END_SRC

**** Notes

A pipeline can be composed of a sequence of processes (because they are themselves emitters). A process can use the
/output/ of a pipeline as its data.

By this point, you've noticed that pipelines and processes can output identical results. This doesn't mean the choice of
which to use is merely one of preference.

Use a process when the data is unknown, use a pipeline otherwise.

*** propagate(emitter, xs)

A workflow helper that maps the execution result of an =emitter= to a collection of =xs=.

**** Parameters

+ =emitter: (x: unknown) => unknown=: the emitter to execute on each value
+ =xs: unknown[]=: the collection of values

**** Returns

=unknown[]=: the collection of results

**** Example

#+BEGIN_SRC deno
const {
  convert,
  mix,
  harmony
} = await import("https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js");
const {
  preset,
  propagate
} = await import("https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/workflow.js");

const swatch = convert("hex", "rebeccapurple");

const scheme = preset(harmony, { configuration: "analogous" });

const light = preset(mix, {target: "#fff", strength: 75, steps: 3});
const dark = preset(mix, {target: "#111", strength: 75, steps: 3});

// Propagate over scheme to create variants
console.log(propagate(light, scheme(swatch)));
// [
//   [ "#8967b4", "#af99ce", "#d6cbe7" ],
//   [ "#a45d98", "#c492ba", "#e2c8dc" ],
//   [ "#b35973", "#d0909f", "#e9c7ce" ]
// ]

console.log(propagate(dark, scheme(swatch)));
// [
//   [ "#4f2c74", "#392451", "#241b30" ],
//   [ "#64225b", "#471e41", "#2c1928" ],
//   [ "#701c3a", "#4f1b2c", "#30181e" ]
// ]
#+END_SRC

**** Notes

Propagation is a tool for when you have a scale of values and want to transform each value with the same emitter. You
can also use it to transform arbitrary groupings of values as long as they're the same type.

Not demonstrated but important to know: =propagate()= can be preset. This means you can slip propagation into processes
and pipelines. From here, even more options for composing complex data open up to the advanced user.

*** delegate(xs, ...emitters)

A workflow helper that maps a collection of =xs= to a sequence of =emitters=.

**** Parameters

+ =xs: unknown[]=: the collection to delegate
+ =emitters: Array<(x: unknown) => unknown>=: the sequence of emitters

**** Returns

+ =unknown[]=: the collection of results

**** Example

#+BEGIN_SRC deno
const {
  convert,
  adjust,
  harmony
} = await import("https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/color.js");
const {
  preset,
  delegate
} = await import("https://cdn.jsdelivr.net/gh/quarksuite/core@2.0.0-26/workflow.js");

const swatch = convert("hex", "rebeccapurple");

const scheme = preset(harmony, { configuration: "analogous" });

// Adjust colors in scheme for greater contrast
console.log(
  delegate(
    scheme(swatch),
    undefined,
    preset(adjust, { lightness: 20, chroma: -10 }),
    preset(adjust, { lightness: -15, chroma: 10 })
  )
); // ["#663399", "#bd6baf", "#680021"]
#+END_SRC

**** Notes

Reach for =delegate()= when you encounter a situation where you have a collection of data and want to assign a different
transformation to each value or /selectively/ alter values.

Not much more to say on that.

* Extending the Library

If you want to extend the library or build particular functionality on top of it, you can do that without much
hassle. QuarkSuite is small and intentionally designed (especially in the shift from v1 to v2) to allow it.

The key is awareness of the *types of data* that QuarkSuite passes around and its simple architectural idioms.

As long as your extensions follow the minimal rules set by the design, you can build as many layers of abstraction on
top as you or your team require.

If you run into any issues with this, please let me know how I can help.

* Next Steps

Now that you have the technical overview of how this all works, give it a try in your own projects. I highly recommend
you follow up this reading with the user handbook if you haven't already. Quite a bit of this documentation makes better
sense in context. Especially advanced usage through the workflow module.

Thanks for reading, and I hope you found it useful.
