#+TITLE: Changelog

All notable changes to this project will be documented in this file.

The format is based on [[https://keepachangelog.com/en/1.0.0/][Keep a Changelog]] and this project adheres to [[https://semver.org/spec/v2.0.0.html][Semantic Versioning]].

* Table of Contents :TOC@3:
- [[#v101---2021-12-17][v1.0.1 - 2021-12-17]]
  - [[#added][Added]]
  - [[#fixed][Fixed]]
- [[#v100---2021-12-16][v1.0.0 - 2021-12-16]]
  - [[#added-1][Added]]
    - [[#revamped-workflow][revamped workflow]]
    - [[#explicit-naming-conventions][explicit naming conventions]]
    - [[#overhauled-api][overhauled API]]
- [[#v021---2020-06-07][v0.2.1 - 2020-06-07]]
  - [[#fixed-1][Fixed]]
    - [[#color-adjustment][color adjustment]]
- [[#v020---2020-05-27][v0.2.0 - 2020-05-27]]
  - [[#added-2][Added]]
    - [[#color-conversion][color conversion]]
  - [[#changed][Changed]]
    - [[#color-adjustment-1][color adjustment]]
    - [[#color-mixture][color mixture]]
    - [[#color-schemes][color schemes]]
    - [[#color-palette-color-scale][+color palette+ color scale]]
- [[#v011---2020-04-29][v0.1.1 - 2020-04-29]]
  - [[#changed-1][Changed]]
    - [[#color-conversion-1][color conversion]]
- [[#v010---2021-04-13][v0.1.0 - 2021-04-13]]
  - [[#added-3][Added]]
    - [[#functional-utilities][functional utilities]]
    - [[#color-conversion-2][color conversion]]
    - [[#scheme-functions][scheme functions]]
    - [[#color-accessibility][color accessibility]]
  - [[#changed-2][Changed]]
    - [[#scheme-functions-1][scheme functions]]
    - [[#output-functions][output functions]]
  - [[#removed][Removed]]
    - [[#functional-utilities-1][functional utilities]]

* v1.0.1 - 2021-12-17

** Added

+ Examples for =utility_compose=, =utility_curry=, =utility_pipe=

** Fixed

+ Malformed TSDoc typing
+ Function documentation typos

* v1.0.0 - 2021-12-16

Quarks System Core v1 is here and it's another major rewrite. To begin, the workflow is a completely
different beast. The naming conventions are more deliberate, the design token spec is more or less
settled, and I've reinforced the library's web focus.

** Added

*** revamped workflow

+ Basic: automatic token generation via bootstrapper
+ Intermediate: manual token generation via formulas
+ Advanced: granular token generation via utilities

*** explicit naming conventions

+ =PascalCase= for bootstrapper/formulas
+ =snake_case= for utilities/exporters
+ conventional =camelCase= for internal functionality

*** overhauled API

+ too much to list, recommend [[https://observablehq.com/@cr-jr/qsc-api-1-0-0][reading it]]

* v0.2.1 - 2020-06-07

** Fixed

*** color adjustment

+ bug where the presence of alpha component was implemented in standard LCh(ab) instead of Oklab,
  which rendered the color adjustment achromatic

* v0.2.0 - 2020-05-27

** Added

*** color conversion

+ Added /non-standard/ Oklab (LCh) color format support

** Changed

*** color adjustment

+ All color adjustment functions are now implemented through the Oklab color space for better hue
  linearity and lightness/chroma predictions
+ Adjustments are perceptually uniform and blue hues no longer shift toward purple

*** color mixture

+ Color mixing now uses simpler interpolation formula through the Oklab color space

*** color schemes

+ All basic color schemes have their output explicitly slotted into a fixed scale. This means
  =custom()= is the only true dyanamic color scheme generator. Use it carefully

*** +color palette+ color scale

+ =color_palette.js= module renamed to =color_scale.js= (which is a better description of its purpose)
+ New interpolation formula makes =contrast= parameter slightly more sensitive (particularly with shades)

* v0.1.1 - 2020-04-29

** Changed

*** color conversion

+ refactored conversion logic to be simpler

* v0.1.0 - 2021-04-13

The initial release of Quarks System Core adds several improvements over QuarkSuite 1. For a full
overview of what's different from legacy, consult the [[https://github.com/quarksuite/legacy/blob/master/CHANGELOG.md#v500---2020-12-05][Changelog of QuarkSuite 1]].

This project no longer relies on Node or NPM and is instead served directly from the Arweave
permaweb via [[https://nest.land][nest.land]]. Use =https://x.nest.land/quarksuite:core/mod.js= in a browser console or in
your scripts to get started.

TypeScript is also gone to remove the compile step that would conflict with using the library in its
target environments. Basic type information is provided for development via TSDoc comments.

Top level source files are now modules by default, and the below modules should be preferred for importing:

+ =mod.js=: the entry point for the entire public API (aggregates the following)
  - =utilities.js=: contains advanced functional utilities
  - =color.js=: contains all color functions
  - =typography.js=: contains all typography functions
  - =modular_scale.js=: contains all functions for using modular scales
  - =design_tokens.js=: contains all build functions

Lastly, I've used literate programming through the development of Quarks System Core to clarify the
implementation details, so you'll find [[https://github.com/quarksuite/core/blob/main/README.org#source-code][the documentation is also the source]].

** Added

*** functional utilities

+ =compose= function for straightforward composition

*** color conversion

+ =device-cmyk=, =hwb=, =lab=, =lch= CSS formats now valid

*** scheme functions

+ simplified =analogous=, =splitComplementary=, =triadic=, =tetradic/dualComplementary=, =square=
  functions provided for basic schemes; no longer need to set modifiers

*** color accessibility

+ =contrast= function for validating or filtering palettes with WCAG color contrast ratios
  recommendations

** Changed

*** scheme functions

+ output of basic schemes slightly rearranged
+ =custom= color scheme generation modified to create colors around the input color symmetrically

*** output functions

+ =yaml= data export added
+ =tw= changed to =tailwind=
+ =sd= changed to =styledict=

** Removed

*** functional utilities

+ =bind= scrapped in favor of JavaScript's native =Function.bind=
